---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/stable/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}_all.deb"
            mode: 755
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            mode: 755
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}"
      with_items:
          - ./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
          - ./clickhouse-client_{{ clickhouse_version }}_all.deb
          - ./clickhouse-server_{{ clickhouse_version }}_all.deb
      notify: Start clickhouse service
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: install Vector
  hosts: clickhouse
  handlers:
    - name: restart vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
  - block:
        - name: get vector distr
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
            dest: "./vector_{{ vector_version }}-1_amd64.deb"
            mode: 755
        - name: Install vector package
          become: true
          ansible.builtin.apt:
            deb: ./vector_{{ vector_version }}-1_amd64.deb
          notify: restart vector
